var LIST_MY_CHOICE;
(function (LIST_MY_CHOICE) {
    LIST_MY_CHOICE[LIST_MY_CHOICE["CBR650R"] = 0] = "CBR650R";
    LIST_MY_CHOICE[LIST_MY_CHOICE["CBR500R"] = 1] = "CBR500R";
    LIST_MY_CHOICE[LIST_MY_CHOICE["CB650R"] = 2] = "CB650R";
})(LIST_MY_CHOICE || (LIST_MY_CHOICE = {}));
var LIST_MY_CHOICE_PRICE;
(function (LIST_MY_CHOICE_PRICE) {
    LIST_MY_CHOICE_PRICE["CBR650R"] = "220";
    LIST_MY_CHOICE_PRICE["CBR500R"] = "130";
    LIST_MY_CHOICE_PRICE["CB650R"] = "200";
})(LIST_MY_CHOICE_PRICE || (LIST_MY_CHOICE_PRICE = {}));
console.log(LIST_MY_CHOICE[0]);
console.log(LIST_MY_CHOICE.CBR500R);
console.log(LIST_MY_CHOICE_PRICE.CBR500R);
